apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: auth-node-app-el
  namespace: demo-dev
  labels:
    app.kubernetes.io/instance: auth-node-app
    backstage.io/kubernetes-id: auth-node-app
spec:
  # serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: ClusterTriggerBinding
          ref: github-pullreq
      interceptors:
        - params:
            - name: eventTypes
              value: ['pull_request']
          ref:
            name: github
        - params:
            - name: git-revision
              value: >-
                (body.ref.contains('main'))
            - name: overlays
              value: null
          ref:
            name: cel
      template:
        ref: auth-node-app-run-pipeline
